name: Unit tests

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Merge the files
        run: |
          printf "1\n../src" > config
          python3 ../tools/merge-files.py < config
        working-directory: ${{ github.workspace }}/tests

      - name: Build the executable
        run: |
          g++ -Wall -Wextra -Werror output.cpp -o test
        working-directory: ${{ github.workspace }}/tests

      - name: Run the tests
        run: |
          ./test
        working-directory: ${{ github.workspace }}/tests
